apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: collaboration
  name: collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collaboration
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: collaboration
    spec:
      containers:
        - image: jayee230/cs3219-collab:v1.0
          name: collaboration-service-container
          ports:
            - containerPort: 3001
              protocol: TCP
            - containerPort: 3002
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/collaboration-service
              name: collaboration-cm0
            - mountPath: /usr/src/collaboration-service/node_modules
              name: collaboration-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: collaboration-cm0
          name: collaboration-cm0
        - name: collaboration-claim1
          persistentVolumeClaim:
            claimName: collaboration-claim1
