apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: collaboration
  name: collaboration
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: collaboration
