services:
  frontend:
    build:
      context:
        ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    container_name: frontend-container
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    command: yarn dev --host 0.0.0.0
  user:
    restart: always
    build:
      context:
        ./user-service
    volumes:
      - ./user-service:/usr/src/user-service
      - /usr/src/user-service/node_modules
    ports:
      - "${USERSVC_PORT:-4000}:4000"
    container_name: user-service-container
  question:
    restart: always
    build:
      context:
        ./question-service
    volumes:
      - ./question-service:/usr/src/question-service
      - /usr/src/question-service/node_modules
    ports:
      - "${QUESTIONSVC_PORT:-3000}:3000"
    container_name: question-service-container
  matching:
    restart: always
    build:
      context:
        ./matching-service
    volumes:
      - ./matching-service:/usr/src/matching-service
      - /usr/src/matching-service/node_modules
    ports:
      - "${MATCHINGSVC_PORT:-5000}:5000"
    container_name: matching-service-container