apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - args:
            - yarn
            - dev
            - --host
            - 0.0.0.0
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: WATCHPACK_POLLING
              value: "true"
            - name: WDS_SOCKET_HOST
              value: 127.0.0.1
          image: jayee230/cs3219-frontend:v1.0
          name: frontend-container
          # imagePullPolicy: Never
          ports:
            - containerPort: 5173
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/frontend/config
              # name: frontend-claim1
              name: frontend-cm0
            - mountPath: /usr/src/frontend
              name: frontend-claim1
            # - mountPath: /usr/src/frontend
            #   name: frontend-claim1  # Use PVC for source code
            # - mountPath: /usr/src/frontend/config
            #   name: frontend-cm0  # Use ConfigMap for configuration
      restartPolicy: Always
      volumes:
        - configMap:
            name: frontend-cm0
          name: frontend-cm0
        - name: frontend-claim1
          persistentVolumeClaim:
            claimName: frontend-claim1
