apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: matching
  name: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: matching
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: matching
    spec:
      containers:
        - image: jayee230/cs3219-matching:v1.0
          name: matching-service-container
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/matching-service
              name: matching-cm0
            - mountPath: /usr/src/matching-service/node_modules
              name: matching-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: matching-cm0
          name: matching-cm0
        - name: matching-claim1
          persistentVolumeClaim:
            claimName: matching-claim1
