apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: collaboration
  name: collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collaboration
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: collaboration
    spec:
      containers:
        - image: jayee230/cs3219-collab:v1.1
          name: collaboration-service-container
          resources:
            requests:
              cpu: "500m"       # Request for CPU (e.g., 500 millicores)
              memory: "512Mi"   # Request for memory 
            limits:
              cpu: "1000m"      # Limit for CPU (e.g., 1000 millicores)
              memory: "1Gi"   # Limit for memory
          # for testing purposes:
          # resources:
          #   requests:
          #     cpu: "100m"        # Minimum CPU request
          #     memory: "128Mi"    # Minimum memory request
          #   limits:
          #     cpu: "500m"       # Maximum CPU limit
          #     memory: "512Mi"   # Maximum memory limit
          ports:
            - containerPort: 3001
              protocol: TCP
            - containerPort: 3002
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/collaboration-service
              name: collaboration-cm0
            - mountPath: /usr/src/collaboration-service/node_modules
              name: collaboration-claim1
          env:
            - name: COLLABORATION_SERVICE_MONGODB_URI # env variable name
              valueFrom:
                secretKeyRef:
                  name: collaboration-service-mongodb-uri
                  key: COLLABORATION_SERVICE_MONGODB_URI
            - name: JDOODLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jdoodle-client-id
                  key: JDOODLE_CLIENT_ID
            - name: JDOODLE_CLIENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jdoodle-client-secret-key
                  key: JDOODLE_CLIENT_SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY

      restartPolicy: Always
      volumes:
        - configMap:
            name: collaboration-cm0
          name: collaboration-cm0
        - name: collaboration-claim1
          persistentVolumeClaim:
            claimName: collaboration-claim1
