apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: question
  name: question
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: question
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: question
    spec:
      containers:
        - image: jayee230/cs3219-question:v1.1
          name: question-service-container
          resources:
            requests:
              cpu: "500m"       # Request for CPU (e.g., 500 millicores)
              memory: "512Mi"   # Request for memory 
            limits:
              cpu: "1000m"      # Limit for CPU (e.g., 1000 millicores)
              memory: "1Gi"   # Limit for memory
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/question-service
              name: question-cm0
            - mountPath: /usr/src/question-service/node_modules
              name: question-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: question-cm0
          name: question-cm0
        - name: question-claim1
          persistentVolumeClaim:
            claimName: question-claim1
