apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user
    spec:
      containers:
        - image: jayee230/cs3219-user:v1.1
          name: user-service-container
          resources:
            requests:
              cpu: "500m"       # Request for CPU (e.g., 500 millicores)
              memory: "512Mi"   # Request for memory 
            limits:
              cpu: "1000m"      # Limit for CPU (e.g., 1000 millicores)
              memory: "1Gi"   # Limit for memory
          ports:
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/user-service
              name: user-cm0
            - mountPath: /usr/src/user-service/node_modules
              name: user-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: user-cm0
          name: user-cm0
        - name: user-claim1
          persistentVolumeClaim:
            claimName: user-claim1
